[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn wsgi_production:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "/app"
FLASK_ENV = "production"
