[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/status"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PYTHONUNBUFFERED = "1"
FLASK_ENV = "production"
FLASK_DEBUG = "False"
