services:
  - type: web
    name: assessment-platform-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app_simple:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120"
    envVars:
      - key: SECRET_KEY
        value: "production-secret-key-2024"
      - key: FLASK_ENV
        value: "production"
