services:
  - type: web
    name: assessment-platform-backend
    env: python
    region: oregon
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        value: "production-secret-key-2024"
      - key: FLASK_ENV
        value: "production"
